import {
  URLS,
} from './';

export const PAGE_ORDER = [
  URLS.LANDING,
  URLS.HOW_LONG_FLIGHT,
  URLS.WHAT_ACTIVITIES,
  URLS.WHAT_COST,
  URLS.WHAT_FOOD,
  URLS.WHAT_TEMPERATURE,
  URLS.RESULTS,
];
